
name: Node CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      
      - name: Clone the git repository code
        uses: actions/checkout@v4

     
      - name: setup nodejs
        uses: actions/setup-node@v4
      
        
      - name: Instal dependencies
        run: make install

       
      - name: Run Eslint
        run: make lint

       
      - name: Run tests
        run: make test

     
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
          
      - name: Upload coverage report to QLTY
        uses: qltysh/qlty-action/coverage@v1
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: coverage/lcov.info 
